export const allProjects = [
  {
    title: "E-Commerce Web App",
    description: "A full-stack e-commerce platform with a seamless shopping experience.",
    image: "/images/hemart-landing-page.png",
    imageAlt: "E-Commerce Web App",
    link: "#",
    tags: ["Web", "E-Commerce", "Full-Stack"],
    repository: "https://github.com/faizalnursaori/Hemart",
    techStack: [
      { title: "Typescript", image: "/images/typescript.png" },
      { title: "NextJS", image: "/images/nextjs.png" },
      { title: "Express.js", image: "/images/expressjs.png" },
      { title: "TailwindCSS", image: "/images/tailwindcss.png" },
      { title: "MySQL", image: "/images/mysql.png" },
    ],
  },
  {
    title: "Event Management System",
    description: "A platform to create and manage events seamlessly.",
    image: "/images/eveny-landing-page.png",
    imageAlt: "Event Management System",
    link: "#",
    repository: "https://github.com/faizalnursaori/Eveny",
    tags: ["Events", "Management", "CRUD"],
    techStack: [
      { title: "Typescript", image: "/images/typescript.png" },
      { title: "NextJS", image: "/images/nextjs.png" },
      { title: "Express.js", image: "/images/expressjs.png" },
      { title: "TailwindCSS", image: "/images/tailwindcss.png" },
      { title: "MySQL", image: "/images/mysql.png" },
    ],
  },
  {
    title: "Dynasty Basketball Landing Page",
    description: "A landing page for Dynasty Basketball.",
    image: "/images/dynasty-landing-page.png",
    imageAlt: "Landing Page of Dynasty",
    link: "https://www.dynastybasketball.web.id/",
    repository: "https://github.com/faizalnursaori/landing-dynasty",
    tags: ["Landing Page"],
    techStack: [
      { title: "Typescript", image: "/images/typescript.png" },
      { title: "NextJS", image: "/images/nextjs.png" },
      { title: "TailwindCSS", image: "/images/tailwindcss.png" },
    ],
  },
  {
    title: "Mini Project",
    description: "A mini project to practice React and TypeScript.",
    image: "/images/mini-project-new.png",
    imageAlt: "Mini project pictures",
    link: "/projects/mini-project",
    repository: "https://github.com/faizalnursaori/",
    tags: ["Events", "Management", "CRUD"],
    techStack: [
      { title: "Typescript", image: "/images/typescript.png" },
      { title: "ReactJS", image: "/images/reactjs.webp" },
      { title: "TailwindCSS", image: "/images/tailwindcss.png" },
    ],
  },
];
