export const mainProjects = [
  {
    title: "E-Commerce Web App",
    slug: "e-commerce-web-app",
    description:
      "A full-stack e-commerce platform with a seamless shopping experience. In this project, I contributed to developing the Shopping Cart, Checkout Process, and Order Management features.",
    image: "/images/hemart-landing-page.png",
    imageAlt: "E-Commerce Web App",
    link: "#",
    tags: ["Web", "E-Commerce", "Full-Stack"],
    features: [
      "Homepage / Landing Page",
      "User Authentication and Profiles",
      "User Address, Location Determination and Shipping Cost Calculation",
      "Store Management ",
      "Admin Account Management",
      "Product Management",
      "Inventory Management",
      "Discount Management",
      "Report & Analysis",
      "Shopping Cart",
      "Checkout Process & Order Tracking",
      "Order Management",
    ],
    repository: "https://github.com/faizalnursaori/Hemart",
    techStack: [
      { title: "Typescript", image: "/images/typescript.png" },
      { title: "NextJS", image: "/images/nextjs.png" },
      { title: "Express.js", image: "/images/expressjs.png" },
      { title: "TailwindCSS", image: "/images/tailwindcss.png" },
      { title: "MySQL", image: "/images/mysql.png" },
    ],
  },
  {
    title: "Event Management System",
    slug: "event-management-system",
    description:
      "A platform for seamlessly creating and managing events. In this project, I contributed to developing the Landing Page, Login/Register Page, Authentication, Authorization, and Event Review features.",
    image: "/images/eveny-landing-page.png",
    imageAlt: "Event Management System",
    link: "#",
    repository: "https://github.com/faizalnursaori/Eveny",
    tags: ["Events", "Management", "CRUD"],
    features: [
      "Event Discovery",
      "Event Details",
      "Authentication",
      "Authorization",
      "Referral Number",
      "Event Management Dashboard",
      "Event Review",
    ],
    techStack: [
      { title: "Typescript", image: "/images/typescript.png" },
      { title: "NextJS", image: "/images/nextjs.png" },
      { title: "Express.js", image: "/images/expressjs.png" },
      { title: "TailwindCSS", image: "/images/tailwindcss.png" },
      { title: "MySQL", image: "/images/mysql.png" },
    ],
  },
  {
    title: "Dynasty Basketball Landing Page",
    slug: "dynasty-basketball-landing-page",
    description:
      "A landing page for Dynasty Basketball. In this project, I contributed to developing the Landing Page",
    image: "/images/dynasty-landing-page.png",
    imageAlt: "Landing Page of Dynasty Basketball",
    link: "https://www.dynastybasketball.web.id/",
    repository: "https://github.com/faizalnursaori/landing-dynasty",
    tags: ["Landing Page"],
    features: ["Landing Page"],
    techStack: [
      { title: "Typescript", image: "/images/typescript.png" },
      { title: "NextJS", image: "/images/nextjs.png" },
      { title: "TailwindCSS", image: "/images/tailwindcss.png" },
    ],
  },
];
